name: Deploy-feature

on:
  push:
    branches: [ feature/* ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Push to Dokku
        run: |
          git remote add dokku dokku@${{ secrets.DOKKU_SERVER }}:${{ secrets.DOKKU_APP }} 2>/dev/null || true
          git push dokku HEAD:main --force
